shell = { program = "/usr/bin/zsh", args = ["-l"] }

# Tinty Start# base16 Catppuccin Mocha - alacritty color config
# https://github.com/catppuccin/catppuccin

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1e1e2e'
foreground = '0xcdd6f4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e1e2e'
cursor = '0xcdd6f4'

# Normal colors
[colors.normal]
black = '0x1e1e2e'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xcba6f7'
cyan = '0x94e2d5'
white = '0xcdd6f4'

# Bright colors
[colors.bright]
black = '0x313244'
red = '0xfab387'
green = '0x181825'
yellow = '0x313244'
blue = '0x585b70'
magenta = '0xf5e0dc'
cyan = '0xf2cdcd'
white = '0xb4befe'
# Tinty End

[font]
size = 15

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[window]
decorations_theme_variant = "Dark"
