[metadata]
name = "channels"
description = "Select a television channel"
requirements = ["tv", "bat"]

[source]
command = ["tv list-channels"]

[preview]
command = "bat --color always ${TELEVISION_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/television}/cable/{}.toml"
shell = "bash"

[keybindings]
enter = "actions:channel-enter"
ctrl-e = "actions:edit"

[actions.channel-enter]
description = "Enter a television channel"
command = "tv {}"
mode = "execute"

[actions.edit]
description = "Opens the selected entries with the default editor (falls back to vim)"
command = "${EDITOR:-vim} ${TELEVISION_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/television}/cable/{}.toml"
shell = "bash"
# use `mode = "fork"` if you want to return to tv afterwards
mode = "execute"
