default-scheme = "base16-catppuccin-mocha"
default-cycle-ring = "catppuccin-plus"
hooks = ["$HOME/Git/dotfiles/local/bin/tinty.bootstrap"]

[[rings]]
name = "catppuccin-plus"
schemes = [
  "base16-catppuccin-latte",
  "base16-catppuccin-frappe",
  "base16-catppuccin-macchiato",
  "base16-catppuccin-mocha",
  "base16-default-dark",
  "base16-tokyo-night-moon",
]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = ". \"$TINTY_THEME_FILE_PATH\""

[[items]]
name = "tinted-alacritty"
path = "https://github.com/tinted-theming/tinted-alacritty"
themes-dir = "colors"
write-to-file = ["~/.config/alacritty/alacritty.toml", "# Tinty Start", "# Tinty End"]

[[items]]
name = "tinted-tmux"
path = "https://github.com/tinted-theming/tinted-tmux"
themes-dir = "colors"
hook = "tmux source-file \"$TINTY_THEME_FILE_PATH\" 2>/dev/null || true"
