# Use vim keybindings in copy mode
setw -g mode-keys vi

# Ensure we can send C-s to the underlying program
bind-key C-s send-prefix -2

# Free the original Ctrl-b prefix keybinding
unbind-key C-b

# Don't suspend-client
unbind-key C-z

# Don't detach from session
unbind-key d

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Yank with 'y' but don't leave visual mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy"


#---------------- Utilities
bind-key n new-window -c '#{pane_current_path}'

bind-key v split-window -h "nvim -c 'GpChatLast'"
bind-key f split-window -h "nvim -c 'GpChatFinder'"

bind-key d display-popup -d ~/zettelkasten -h 90% -w 90% -E "NVIM_APPNAME=next vi +'Telekasten goto_today'"

# Run new ai chat, resume last one or find
# bind-key <tbd> display-popup -d ~/zettelkasten -h 90% -w 90% -E "NVIM_APPNAME=next vi +'GpChatNew'"
# bind-key <tbd> display-popup -d ~/zettelkasten -h 90% -w 90% -E "NVIM_APPNAME=next vi -c 'GpChatToggle vsplit' -c 'norm G' -c 'only'"

bind-key t display-popup -d ~/zettelkasten -h 90% -w 90% -E "nvim TODO.md"
bind-key j display-popup -d ~/zettelkasten -h 90% -w 90% -E "nvim JOUR.md"
bind-key 0 display-popup -d ~/zettelkasten/Projects/ -h 90% -w 90% -E "nvim +'Oil'"


bind-key h display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "htop"
bind-key g display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "git fuzzy status"

bind-key \' display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "lazygit"
bind-key \" display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "git fuzzy status"
bind-key \; display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "lazydocker"
bind-key \: display-popup -d '#{pane_current_path}' -h 90% -w 90% -E "oxker"


# Unbind l to jump between two last windows. Use it to clear the screen
unbind-key l
bind-key l send-keys 'C-l'

# Free binds
# o
# C-o
# C-j
# C-g
