set -g base-index 1
set-window-option -g pane-base-index 1

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

set -g @catppuccin_flavor 'mocha'

# Window

set -g @@catppuccin_status_background "#{@thm_surface_1}"

## Window global/default configuration
#set -g @catppuccin_window_default_text " #{window_name}"
#set -g @catppuccin_window_status "icon"
#set -g @catppuccin_window_default_fill "number"
#set -g @catppuccin_window_number_position "left"

# Menu styling options
set -g @catppuccin_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_overlay_0}"

set -g @catppuccin_window_status_style "custom" # basic, rounded, slanted, custom, or none
set -g @catppuccin_window_text_color "#{@thm_surface_1}"
set -g @catppuccin_window_number_color "#{@thm_blue}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_current_text_color "#{@thm_surface_0}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number "#I"
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator " "

set -g @catppuccin_window_current_left_separator "  "
set -g @catppuccin_window_current_middle_separator "  "
set -g @catppuccin_window_current_right_separator " "

# Status line options
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█  "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_middle_separator ""
set -g @catppuccin_status_connect_separator "no" # yes, no
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"

# Status modules config
set -g @catppuccin_date_time_text "%d-%m %H:%M"

# Run plugin
run '~/.config/tmux/plugins/tmux/catppuccin.tmux' # or where this file is located on your machine

# ... and then set status-left & status-right ...
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_date_time}"

