run '~/.config/tmux/plugins/tmux/catppuccin.tmux' # or where this file is located on your machine

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux#2.3.0'


# bootstrap tpm
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"


# General

bind-key C-r source-file "~/.config/tmux/tmux.conf" \; display-message "~/.tmux.conf reloaded"

set -g default-shell /usr/bin/zsh
set -g default-command /usr/bin/zsh

set -g prefix C-s
set -g prefix2 C-s

set -s escape-time 1
set -g history-limit 100000

# Improve colors: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Source Parts
source '/home/max/.config/tmux/status.conf'
source '/home/max/.config/tmux/navigation.conf'
source '/home/max/.config/tmux/keybinds.conf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
