[tools]
"aqua:joshmedeski/sesh" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:zk-org/zk" = "latest"
atuin = "latest"
bat = "latest"
bottom = "latest"
carapace = "latest"
delta = "latest"
doggo = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
glow = "latest"
gum = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
opencode = "latest"
oxker = "latest"
pi = "latest"
"cargo:tinty" = "latest"
ripgrep = "latest"
starship = "latest"
television = "latest"
yq = "latest"
zoxide = "latest"
rust = "latest"

[tools."github:michel-kraemer/zsh-patina"]
version = "latest"

[tools."github:michel-kraemer/zsh-patina".platforms]
linux-x64   = { asset_pattern = "zsh-patina-*-x86_64-unknown-linux-gnu.tar.gz" }
macos-arm64 = { asset_pattern = "zsh-patina-*-aarch64-apple-darwin.tar.gz" }
