[tools]
"aqua:joshmedeski/sesh" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
bat = "latest"
carapace = "latest"
delta = "latest"
doggo = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
opencode = "latest"
oxker = "latest"
ripgrep = "latest"
starship = "latest"
television = "latest"
zoxide = "latest"
